services:
  minecraft-server-backup:
    container_name: mc-${SERVER_DIR}-backup
    image: docker.io/itzg/mc-backup
    restart: unless-stopped
    env_file:
      - ../env/.backup.env
      - ../../servers/${SERVER_DIR}/config.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../../servers/${SERVER_DIR}:/data:ro
      - ${BACKUP_DIR}/${SERVER_DIR}:/backups
