services:
  minecraft-server:
    container_name: mc_${SERVER_TYPE}_${CREATED_AT}_${CONTAINER_NAME:-${MODPACK_NAME:-}}
    image: docker.io/itzg/minecraft-server:java${JAVA_VERSION}
    tty: true
    stdin_open: true
    stop_grace_period: 30s
    restart: unless-stopped
    secrets:
      - curseforge_api_key
    env_file:
      - ../platforms/.${SERVER_TYPE}.env
      - ../env/.container.env
      - ../env/.downloaders.env
      - ../env/.java.env
      - ../env/.players.env
      - ../env/.properties.env
    ports:
      - ${SERVER_PORT:-25565}:25565/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${SERVER_DIR}/${SERVER_TYPE}_${CREATED_AT}_${CONTAINER_NAME:-${MODPACK_NAME:-}}:/data
      - ${SERVER_DIR}/${SERVER_TYPE}_${CREATED_AT}_${CONTAINER_NAME:-${MODPACK_NAME:-}}/local-config:/config
      - ${SERVER_DIR}/${SERVER_TYPE}_${CREATED_AT}_${CONTAINER_NAME:-${MODPACK_NAME:-}}/local-mods:/mods
      - ${SERVER_DIR}/${SERVER_TYPE}_${CREATED_AT}_${CONTAINER_NAME:-${MODPACK_NAME:-}}/local-plugins:/plugins
      - ${SERVER_DIR}/${SERVER_TYPE}_${CREATED_AT}_${CONTAINER_NAME:-${MODPACK_NAME:-}}/local-data:/host
    labels:
      com.centurylinklabs.watchtower.enable: false
